spring:
  application:
    name: TimesheetRegister
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheets
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true